DATASET:
    train_list: ['FreiHAND']
    test_list: ['FreiHAND']
    input_joint_set: 'mano'
    target_joint_set: 'mano'
    workers: 16
    use_gt_input: False

MODEL:
    name: 'posenet'
    input_shape: [384, 288]

TRAIN:
    print_freq: 10
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 120
    scheduler: 'step'
    lr: 0.001
    lr_step: [90]
    lr_factor: 0.1
    optimizer: 'rmsprop'

AUG:
    flip: True
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
    weight_path: './experiment/posenet_manoJ_train_freihand'
