DATASET:
    train_list: ['Human36M', 'COCO', 'MuCo']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'coco'
    workers: 16
    use_gt_input: False

MODEL:
    name: 'posenet'
    input_shape: [384, 288]

TRAIN:
    print_freq: 10
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 30
    scheduler: 'step'
    lr: 0.001
    lr_step: [20]
    lr_factor: 0.1
    optimizer: 'rmsprop'

AUG:
    flip: True
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False