DATASET:
    train_list: ['FreiHAND']
    test_list: ['FreiHAND']
    input_joint_set: 'mano'
    target_joint_set: 'mano'
    workers: 16
    use_gt_input: False

MODEL:
    name: 'pose2mesh_net'
    input_shape: [384, 288]
    normal_loss_weight: 0.1
    edge_loss_weight: 20
    joint_loss_weight: 0.001
    posenet_pretrained: True
    posenet_path: './experiment/posenet_manoJ_train_freihand/final.pth.tar'

TRAIN:
    print_freq: 10
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 40
    edge_loss_start: 15
    scheduler: 'step'
    lr: 0.001
    lr_step: [30]
    lr_factor: 0.1
    optimizer: 'rmsprop'

AUG:
    flip: False
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
